import minitel.apps_annonces
import minitel.apps_chat
import minitel.apps_elections
import minitel.apps_fesste
import minitel.apps_forking
import minitel.apps_horoscope
import minitel.apps_index
import minitel.apps_quest
import minitel.apps_static
import minitel.apps_system
import minitel.apps_trombinet
import minitel.apps_wanted
import minitel.apps_wiki
