import logging
import minitel.tc as tc
from minitel.apps import BaseApp, register, appForCode
from minitel.assets import asset
from bisect import bisect
import random


@register("horoscope", ["astro"])
class HoroscopeApp(BaseApp):
    def interact(self):
        self.m.sendfile(asset("fesste/HOROSCOPE.vdt"))
        self.m.pos(24, 31)
        self.m._write(tc.ESC + tc.tVideoInverseStart)
        self.m.print("ENVOI")
        signe = self.m.addInputField(24, 28, 2, "")
        self.m.keyHandlers[tc.kEnvoi] = tc.Break
        self.m.handleInputsUntilBreak()
        self.show_results()
    
    def show_results(self):
        self.m.reset()
        fortune = random.choice(self.fortunes)
        self.m.clear()
        self.m.pos(3, 1)
        self.m._write(tc.tFgColor(tc.clYellow))
        self.m.print(fortune)
        self.m.keyHandlers[tc.kEnvoi] = tc.Break
        self.m.handleInputsUntilBreak()

    fortunes = [
        "Des opportunites professionnelles vont se presenter a toi dans les prochaines semaines. Tu seras reconnu pour tes competences et ton travail acharne, ce qui pourrait te mener a une promotion ou a un nouveau poste passionnant. Dans le domaine sentimental, de belles rencontres t'attendent dans un futur proche. Tu seras charme par une personne au caractere unique et cette relation te fera decouvrir de nouvelles emotions. Laisse-toi guider par ton coeur et profite de ces moments magiques.",
        "Cette semaine, vous serez sous l'influence de la chance et de l'optimisme. Au travail, votre creativite et votre determination vous permettront de realiser des projets ambitieux. Votre perseverance sera recompensee et vous pourriez meme recevoir une promotion ou une opportunite interessante. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Que vous soyez celibataire ou en couple, l'amour sera au rendez-vous et vous pourriez faire la rencontre d'une personne qui vous fera vibrer. N'hesitez pas a sortir de votre zone de confort et a vous laisser surprendre par les hasards de la vie. Cette semaine, l'univers vous reserve de belles surprises.",
        "Cette semaine sera placee sous le signe de la reussite professionnelle pour toi ! Grace a ton devouement et ta perseverance, tu seras reconnu(e) a ta juste valeur et recompense(e) pour tes efforts. Tu pourrais meme recevoir une proposition interessante pour un nouveau projet ou une promotion. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Laisse-toi surprendre par l'amour, il pourrait bien frapper a ta porte de maniere inattendue. Garde l'esprit ouvert et laisse-toi seduire par ces nouvelles opportunites amoureuses. Tu pourrais etre agreablement surpris(e) par ce que le destin a en reserve pour toi.",
        "Au travail, de nouvelles opportunites s'offrent a toi ! Tu te demarqueras par ta creativite et ton professionnalisme, ce qui attirera l'attention de tes superieurs. N'hesite pas a proposer tes idees et a prendre des initiatives, cela te menera vers de belles reussites. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Laisse-toi surprendre par ces nouvelles personnes qui pourraient bien bouleverser ta vie amoureuse. Ouvre ton coeur et laisse l'amour entrer, de belles surprises t'attendent !",
        "Ce mois-ci, les astres sont alignes pour vous apporter de belles opportunites dans votre vie professionnelle. Vous serez inspire, creatif et votre travail sera reconnu a sa juste valeur. Des projets passionnants pourraient egalement voir le jour, vous permettant d'evoluer et de vous epanouir pleinement. Du cote de votre vie amoureuse, de belles rencontres sont a prevoir. Vous pourriez croiser la route d'une personne qui vous fera vibrer et avec qui vous partagerez une belle complicite. Laissez-vous guider par vos sentiments et vivez pleinement ces moments magiques qui vous attendent. N'ayez pas peur de vous ouvrir a l'amour, de belles surprises vous attendent dans un futur proche.",
        "Dans les semaines a venir, les astres vont briller de mille feux pour toi ! Cote travail, tu vas enfin pouvoir concretiser tes projets et atteindre tes objectifs. Tu seras recompense pour tes efforts et ton travail acharne. Des opportunites de carriere interessantes se presenteront a toi, n'hesite pas a les saisir. Dans ta vie amoureuse, de belles rencontres sont a prevoir. Tu pourrais bien croiser le chemin de quelqu'un de special qui saura te faire vibrer. Laisse-toi guider par ton coeur et profite de ces moments de bonheur a deux.",
        "Dans les prochains jours, vous aurez une energie debordante et une forte motivation au travail. Vous serez capable de relever tous les defis et de mener a bien vos projets. Votre determination et votre perseverance seront recompensees par une promotion ou une augmentation de salaire. Cote coeur, de belles rencontres s'annoncent. Vous pourriez croiser le chemin d'une personne speciale qui fera battre votre coeur. Laissez-vous guider par vos emotions et ne ratez pas cette opportunite de vivre une belle histoire d'amour. Soyez ouvert(e) aux nouvelles experiences et vous serez surpris(e) par les belles surprises que la vie vous reserve.",
        "Ton avenir professionnel s'annonce prometteur ! Tu seras reconnu pour tes talents et tes competences, ce qui te permettra d'atteindre de nouveaux sommets dans ta carriere. De belles opportunites se presenteront a toi, alors n'hesite pas a saisir les defis qui se presenteront. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Que ce soit en amour ou en amitie, tu seras entoure de personnes positives et bienveillantes qui t'apporteront beaucoup de bonheur. Laisse-toi porter par les belles emotions qui t'attendent et profite de chaque instant.",
        "Cette semaine, les astres te reservent de belles surprises, surtout dans ton domaine professionnel. Tu feras preuve d'une grande creativite et de nouvelles opportunites se presenteront a toi. Tu seras egalement entoure de personnes positives qui t'aideront a atteindre tes objectifs. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Que ce soit en amitie ou en amour, tu seras charme par de nouvelles personnes qui t'apporteront de la joie et de la douceur dans ta vie. Laisse-toi porter par ces nouvelles rencontres et profite de chaque instant !",
        "Cette semaine, les astres te reservent de belles surprises ! Cote travail, tu seras inspire et productif, te permettant de realiser des projets ambitieux. Tu pourras egalement compter sur le soutien de tes collegues pour mener a bien tes missions. Dans le domaine amoureux, de nouvelles rencontres s'annoncent, pleines de complicite et de passion. Laisse-toi guider par ton coeur et ouvre-toi a de belles opportunites. Sois confiant, l'avenir te reserve de merveilleuses surprises !",
        "Dans les prochains jours, votre vie professionnelle sera en plein essor. Des opportunites interessantes se presenteront a vous et vous saurez les saisir avec assurance et determination. Votre creativite sera mise en avant et vous pourriez meme obtenir une promotion ou une augmentation salariale. Cote coeur, de belles rencontres sont a prevoir. Que vous soyez celibataire ou en couple, de nouvelles personnes viendront enrichir votre vie et vous apporteront beaucoup de joie et de bonheur. N'hesitez pas a ouvrir votre coeur et a vous laisser surprendre par ces nouvelles rencontres prometteuses.",
        "Cette semaine, les astres sont alignes en votre faveur. Cote travail, vous avez toutes les chances de reussir. Vos projets aboutiront et vos efforts seront recompenses. Restez determine(e) et perseverant(e), le succes est a portee de main. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Vous pourriez tomber sous le charme d'une personne intrigante et passionnante. Laissez-vous guider par vos emotions et suivez votre instinct, cela pourrait etre le debut d'une belle histoire d'amour.",
        "Cette semaine, les astres te promettent une belle opportunite dans le domaine professionnel. Grace a tes efforts et ta determination, tu pourrais etre recompense(e) par une promotion ou une augmentation salariale. Ne laisse pas passer cette chance, car elle pourrait t'ouvrir de nouvelles portes vers la reussite. Cote coeur, de belles rencontres pourraient se profiler a l'horizon. Que tu sois celibataire ou en couple, les etoiles te reservent de belles surprises. Sois ouvert(e) et laisse-toi guider par ton coeur, car le destin pourrait te reserver une belle surprise. Prends des risques et laisse l'amour entrer dans ta vie. Tu ne le regretteras pas.",
        "Cette semaine, les astres te reservent de belles surprises tant sur le plan professionnel que sentimental. Tu auras l'opportunite de faire des rencontres enrichissantes dans ton domaine de travail, qui pourraient t'ouvrir de nouvelles portes et te permettre d'avancer vers tes objectifs. Au niveau sentimental, une personne speciale pourrait entrer dans ta vie et te faire vivre de beaux moments remplis de complicite et de passion. Garde l'esprit ouvert et laisse la magie operer, les etoiles sont de ton cote !",
        "Dans les prochains jours, les astres te reservent de belles surprises ! Cote travail, tu vas faire preuve d'une grande creativite et d'une determination sans faille. Tu sauras saisir les opportunites qui s'offrent a toi et tu seras recompense pour tes efforts. Une promotion ou une reconversion professionnelle sont a prevoir. Dans ta vie amoureuse, des rencontres inattendues vont changer ta vie. Tu vas faire la connaissance de personnes qui te correspondent vraiment et qui pourraient bien devenir des partenaires de vie. Profite de ces moments magiques pour t'ouvrir a l'amour et a de nouvelles experiences.",
        "Cette semaine, les astres sont en votre faveur ! Au travail, votre determination et votre creativite seront remarquees par vos superieurs, ce qui vous ouvrira de nouvelles opportunites. Vous pourriez egalement recevoir une offre professionnelle allechante. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Vous pourriez croiser le chemin d'une personne speciale et ressentir une connexion instantanee. Laissez-vous guider par vos emotions et ne craignez pas de prendre des risques. Cette nouvelle relation pourrait apporter de la passion et du bonheur dans votre vie. Ouvrez votre coeur et laissez-vous surprendre !",
        "Cet ete, les astres te reservent de belles surprises, cher ami ! Cote travail, tu vas enfin recolter les fruits de tes efforts. Les opportunites se multiplient et tu es plus que pret a les saisir. Ta determination et ton energie seront recompensees, fais-nous confiance ! Mais ce n'est pas tout, cote coeur, de belles rencontres t'attendent. Que tu sois celibataire ou en couple, l'amour sera au rendez-vous. Sois ouvert et laisse-toi surprendre, car la personne qui illuminera ton coeur pourrait bien se trouver juste a cote de toi. Bonne chance !",
        "Cette semaine, les astres sont en faveur de votre reussite professionnelle. Vous allez faire preuve de creativite et de determination, ce qui vous permettra de briller dans votre travail. Vos idees seront appreciees et vous pourriez meme recevoir une promotion ou une opportunite interessante. Du cote de votre coeur, de belles rencontres sont a prevoir. Vous pourriez croiser le chemin d'une personne speciale qui illuminera votre vie. Soyez ouvert(e) aux nouvelles rencontres, elles pourraient vous apporter beaucoup de bonheur et de joie. Gardez confiance en vous et laissez votre coeur guider vos pas.",
        "Cette semaine, les astres te reservent de belles surprises dans ta vie professionnelle. Tu pourrais etre confronte a de nouveaux defis, mais tu sauras les relever avec brio grace a ton devouement et ta perseverance. Les opportunites ne manqueront pas, alors n'hesite pas a saisir celles qui se presentent a toi. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Que tu sois celibataire ou en couple, l'amour sera au rendez-vous. Sois ouvert(e) aux nouvelles experiences et laisse-toi surprendre par cette personne qui pourrait bien changer ta vie. N'oublie pas de prendre du temps pour toi et de t'ecouter, cela t'aidera a trouver l'equilibre dans ta vie personnelle et professionnelle.",
        "Cette semaine, les astres te reservent de belles opportunites sur le plan professionnel. Tu auras l'occasion de mettre en avant tes talents et de briller dans ton domaine. N'hesite pas a prendre des risques et a sortir de ta zone de confort, car cela pourrait t'ouvrir de nouvelles portes. Cote coeur, les planetes te promettent de belles rencontres. Que tu sois en couple ou celibataire, tu pourrais croiser la route d'une personne qui te fera vibrer et avec qui tu partageras de beaux moments. Laisse-toi guider par tes emotions et profite de ces rencontres inattendues.",
        "Dans les semaines a venir, de nouvelles opportunites s'offriront a toi sur le plan professionnel. Les astres seront de ton cote et t'apporteront succes et reconnaissance dans tes projets. Ton travail sera recompense et tu pourras enfin recolter les fruits de tes efforts. Cependant, ne neglige pas ta vie amoureuse car de belles rencontres t'attendent egalement. Tu pourrais croiser le chemin de quelqu'un de special et vivre une belle histoire d'amour. Garde les yeux ouverts et laisse-toi surprendre par le destin.",
        "Cette semaine, les astres sont alignes en ta faveur, cher ami. Au travail, tu fais preuve d'une determination sans faille et cela ne passe pas inapercu. Tes efforts seront enfin recompenses par une promotion ou une belle opportunite professionnelle. Cote coeur, des rencontres inattendues sont a prevoir dans les jours a venir. Tu seras charme par une personne au charme envoutant et cela pourrait bien etre le debut d'une belle histoire. Laisse-toi porter par le destin et profite de ces moments magiques qui t'attendent.",
        "Cette semaine, les astres te reservent de belles surprises ! Cote travail, tu vas enfin voir les fruits de tous tes efforts. Ton professionnalisme sera reconnu et tu pourras meme recevoir une promotion ou une augmentation. Continue sur cette lancee et tu atteindras bientot tes objectifs les plus ambitieux. Quant a ton coeur, de belles rencontres sont a prevoir. Que ce soit en amitie ou en amour, de nouvelles personnes vont entrer dans ta vie et apporter de la joie et de la legerete. Laisse-toi guider par tes emotions et tu decouvriras des personnes incroyables qui illumineront ton quotidien. Profite de ces moments magiques qui t'attendent !",
        "Cette semaine, les astres te reservent de belles surprises ! Cote travail, tu vas beneficier d'une energie debordante et d'une creativite sans limite. Tu sauras prendre des initiatives et tes idees seront tres appreciees par tes superieurs. De plus, de nouvelles opportunites professionnelles pourraient se presenter a toi, alors reste a l'affut ! Cote coeur, les astres te promettent de belles rencontres dans un futur proche. Tu pourrais croiser la route de quelqu'un de special qui fera battre ton coeur. N'hesite pas a prendre des risques et a suivre tes sentiments, tu pourrais etre agreablement surpris. Profite de ces belles energies pour avancer vers un avenir radieux !",
        "Dans les prochains jours, vous allez faire face a de nombreuses opportunites dans votre vie professionnelle. Votre determination et votre perseverance seront recompensees et vous pourriez meme recevoir une promotion ou une nouvelle offre d'emploi interessante. Au niveau du coeur, de belles rencontres sont a prevoir. Que vous soyez celibataire ou en couple, de nouvelles personnes vont entrer dans votre vie et vous apporter de la joie et de la legerete. Laissez-vous surprendre et profitez de ces belles connexions pour creer de nouvelles amities ou peut-etre meme trouver l'amour. Gardez un esprit ouvert et suivez votre instinct, de grandes surprises vous attendent.",
        " Tu vas traverser une periode tres positive sur le plan professionnel. Des opportunites interessantes vont se presenter a toi et tu sauras les saisir avec brio. Ton travail sera reconnu a sa juste valeur et tu pourrais meme recevoir une promotion ou une augmentation salariale. Dans ton coeur, de belles rencontres sont a prevoir dans un futur proche. Que ce soit en amitie ou en amour, de nouvelles personnes vont entrer dans ta vie et t'apporter beaucoup de bonheur. Laisse-toi surprendre et profite de ces moments de complicite et de partage.",
        " Dans les prochains jours, les astres te reservent une periode positive et productive dans le domaine du travail. Tu auras la possibilite de mettre en avant tes competences et de briller dans ton domaine. Les opportunites ne manqueront pas et tu pourrais meme recevoir une promotion ou une augmentation salariale. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Que tu sois celibataire ou en couple, l'amour sera au rendez-vous. Tu pourrais faire la rencontre de quelqu'un de tres special qui fera vibrer ton coeur et qui pourrait bien devenir une personne importante dans ta vie. Laisse-toi guider par tes emotions et ouvre-toi aux surprises que l'univers te reserve.",
        "Dans les semaines a venir, vous pourriez etre confronte a des defis dans votre vie professionnelle. Mais ne vous decouragez pas, car vous serez soutenu par des collegues et des superieurs qui reconnaitront vos efforts et votre devouement. Sur le plan sentimental, de belles rencontres sont a prevoir. Que ce soit dans votre cercle d'amis ou lors d'evenements sociaux, une personne speciale pourrait entrer dans votre vie et apporter une nouvelle energie a votre coeur. Soyez ouvert et pret a saisir les opportunites qui se presentent a vous.",
        "Dans les prochains jours, de nouvelles opportunites se presenteront a toi dans le domaine professionnel. Ne crains pas de sortir de ta zone de confort et de relever de nouveaux defis. Tu as toutes les capacites pour reussir et atteindre tes objectifs. En amour, de belles rencontres sont a prevoir. Laisse-toi surprendre par ces nouvelles personnes qui pourraient changer ta vie. Laisse parler ton coeur et ouvre-toi a de nouvelles possibilites.",
        "Cette semaine, les astres te reservent de belles surprises tant sur le plan professionnel que sentimental. Au travail, tu seras inspire et determine, ce qui te permettra de realiser des projets ambitieux. Tu auras egalement l'occasion de faire de nouvelles rencontres qui pourraient etre benefiques pour ta carriere. Cote coeur, les astres sont en faveur d'une belle rencontre qui pourrait bien changer ta vie. Laisse-toi guider par ton intuition et ouvre-toi aux opportunites qui s'offrent a toi. L'amour sera au rendez-vous et pourrait t'apporter une grande dose de bonheur et de complicite. Profite de ce moment pour t'epanouir pleinement dans toutes les spheres de ta vie.",
        "Dans les prochains jours, vous ressentirez une energie positive et dynamique dans votre vie professionnelle. Vos idees seront creatives et vos competences seront reconnues par vos superieurs. Vous pourriez meme recevoir une promotion ou une augmentation salariale. Cote coeur, de belles rencontres sont prevues dans un futur proche. Vous pourriez croiser le chemin d'une personne speciale qui vous fera battre le coeur plus fort. Soyez ouvert aux nouvelles opportunites et laissez-vous guider par vos emotions. Une belle histoire d'amour pourrait bien commencer pour vous. Soyez confiant et laissez-vous porter par le destin.",
        "Cette semaine, les astres te reserveront de belles surprises ! Cote travail, tu seras plein d'energie et de motivation, pret a relever tous les defis. Tu seras remarque pour tes competences et tes idees novatrices, ce qui pourrait te valoir une promotion ou une opportunite interessante. Dans ta vie amoureuse, de belles rencontres sont a prevoir. Si tu es en couple, votre complicite sera renforcee et de nouvelles aventures vous attendent. Si tu es celibataire, ouvre les yeux, l'amour pourrait te surprendre au coin de la rue. Laisse-toi guider par ton coeur et tu seras comble(e) !",
        "Dans les prochains jours, les astres te reservent de belles surprises cote travail. Tu seras reconnu(e) pour tes competences et ton devouement, ce qui pourrait te valoir une promotion ou une nouvelle opportunite professionnelle. Tu te sentiras epanoui(e) et confiant(e) dans ton domaine. Cote coeur, des rencontres inattendues pourraient se presenter a toi. Laisse parler ton coeur et n'aie pas peur de t'ouvrir aux nouvelles possibilites. Une relation prometteuse pourrait se former dans un futur proche. Reste optimiste et fais confiance a l'univers, il te reserve de belles surprises.",
        "Ton avenir s'annonce radieux, cher ami ! Au travail, tu vas enfin recolter les fruits de tes efforts. Ta perseverance et ta determination vont etre recompensees par une promotion ou une augmentation salariale bien meritee. Cote coeur, de belles rencontres t'attendent dans un futur proche. L'univers va mettre sur ton chemin des personnes exceptionnelles, pretes a partager de merveilleux moments avec toi. Laisse-toi guider par ton intuition et profite de ces instants magiques. Tu vas decouvrir de nouvelles facettes de toi-meme et vivre des experiences inoubliables. Crois en toi et en l'amour, car de belles surprises t'attendent.",
        "Dans les prochaines semaines, votre vie professionnelle sera en pleine expansion. Vous ferez preuve de creativite et de determination, ce qui vous permettra de realiser des projets ambitieux et d'obtenir des resultats impressionnants. Votre travail sera reconnu et vos efforts seront recompenses. Cote coeur, de belles rencontres sont a prevoir. Vous serez attire par des personnes passionnantes et authentiques, pretes a partager de merveilleux moments avec vous. Vous pourriez bien trouver l'amour ou renforcer vos liens avec un etre cher. Laissez-vous guider par vos emotions et profitez de ces nouvelles rencontres pour vous epanouir pleinement.",
        "Cette semaine, le ciel vous reserve de belles surprises, chers amis ! Cote travail, vous allez enfin voir vos efforts recompenses. Une promotion, une augmentation ou une nouvelle opportunite pourrait se presenter a vous. Profitez-en pour montrer votre talent et votre determination. Dans le domaine sentimental, de belles rencontres pourraient avoir lieu dans un futur proche. Laissez-vous surprendre par l'amour et ouvrez votre coeur a de nouvelles possibilites. N'ayez pas peur de prendre des risques, cela pourrait vous mener vers une relation passionnante et durable. Gardez confiance en vous et laissez la magie operer.",
        "Dans les prochains jours, de belles opportunites professionnelles se presenteront a toi. Tu seras reconnu pour tes competences et tes idees innovantes, ce qui te permettra de briller dans ton domaine. Cependant, n'oublie pas de prendre du temps pour toi et de te ressourcer regulierement. Cote coeur, de belles rencontres sont a prevoir. Que ce soit en amitie ou en amour, de nouvelles personnes entreront dans ta vie et apporteront du bonheur et de la joie. Reste ouvert aux nouvelles experiences et laisse-toi surprendre par les belles surprises que l'avenir te reserve.",
        "Pour cette nouvelle periode, les astres te promettent de belles opportunites professionnelles. Tu auras l'occasion de mettre en valeur tes talents et de briller dans ton domaine. N'hesite pas a sortir de ta zone de confort et a saisir les occasions qui se presentent a toi. Ton travail sera recompense et tu pourrais meme recevoir une promotion ou une augmentation. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Que tu sois celibataire ou en couple, l'amour sera au rendez-vous. Tu pourrais faire la rencontre d'une personne qui te correspond parfaitement et avec qui tu partageras de beaux moments. Si tu es en couple, ton lien se renforcera et tu pourras profiter d'une periode harmonieuse et complice avec ton partenaire. Laisse-toi guider par ton coeur et ouvre toi a ce qui vient.",
        "Dans les semaines a venir, vous allez ressentir un regain d'energie et de motivation dans votre vie professionnelle. Les astres sont en votre faveur pour vous aider a atteindre vos objectifs et a reussir dans vos projets. Vous serez egalement entoure de personnes bienveillantes et inspirantes, ce qui vous permettra de developper de nouvelles idees et de concretiser vos ambitions. Cote coeur, de belles rencontres sont prevues dans un futur proche. Que vous soyez en couple ou celibataire, l'amour sera au rendez-vous et vous apportera de la joie et de l'epanouissement. Soyez ouvert aux opportunites qui se presenteront a vous, car elles seront synonymes de bonheur et de complicite.",
        "Dans les prochains jours, de belles opportunites se presenteront a vous dans le domaine professionnel. Votre travail sera reconnu et apprecie, ce qui vous apportera une grande satisfaction et une augmentation de vos responsabilites. Cela vous permettra egalement de faire de nouvelles rencontres enrichissantes, tant sur le plan amical que sentimental. En effet, de belles rencontres vous attendent dans votre vie amoureuse, vous permettant de construire de solides relations basees sur la confiance et la complicite. Vous serez epanoui(e) tant sur le plan personnel que professionnel, profitez-en pleinement !",
        "Dans les semaines a venir, vous pourrez compter sur un alignement des planetes favorable dans votre vie professionnelle. Les opportunites seront nombreuses et vous saurez les saisir avec brio. Votre travail sera reconnu a sa juste valeur et vous pourrez en recolter les fruits. Du cote de votre coeur, de belles rencontres sont a prevoir. Vous pourriez bien croiser le chemin d'une personne qui saura vous faire vibrer et vous apporter beaucoup de bonheur. Laissez-vous guider par vos emotions et profitez de ces moments magiques qui vous attendent.",
        "Dans les prochains jours, les astres seront en votre faveur, cher(e) ami(e). Cote travail, votre perseverance et votre determination ne passeront pas inapercues. Vous serez recompense(e) par une promotion ou une augmentation bien meritee. De plus, de nouvelles opportunites se presenteront a vous, n'hesitez pas a les saisir. Du cote de votre coeur, des rencontres inattendues et passionnantes sont a prevoir. Laissez-vous surprendre par ces nouvelles personnes qui pourraient bien changer votre vie. L'amour sera au rendez-vous et vous promet de belles emotions. Profitez de ces moments de bonheur et ouvrez votre coeur a de nouvelles experiences.",
        "Dans les prochains jours, les astres seront en faveur de votre reussite professionnelle. Vous serez dynamique, perseverant et vos efforts seront recompenses. De nouvelles opportunites s'offriront a vous, ne les laissez pas passer ! Cote coeur, de belles rencontres sont a prevoir. Vous serez attire par des personnes au charme irresistible et ces rencontres pourraient bien changer votre vie amoureuse. Laissez-vous porter par le destin et profitez de ces moments magiques qui s'annoncent. Vous serez comble(e) sur tous les plans !",
        "Dans les jours a venir, les astres te reservent de belles opportunites professionnelles. Tu seras reconnu pour tes talents et ta determination, ce qui te permettra d'avancer vers tes objectifs avec succes. Ton travail sera recompense et tu pourrais meme recevoir une promotion ou une offre interessante. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Que tu sois celibataire ou en couple, tu attireras les regards et pourrais vivre des moments passionnes et remplis de complicite. Laisse-toi porter par ces nouvelles rencontres et profite de chaque instant avec optimisme et legerete.",
        "Pour les prochaines semaines, les astres te reservent de belles opportunites tant sur le plan professionnel que sentimental. Au travail, ta determination et ton professionnalisme seront remarques et te permettront d'atteindre tes objectifs. De nouvelles rencontres enrichissantes sont egalement prevues, que ce soit en amitie ou en amour. Tu pourrais meme faire la rencontre de quelqu'un de special qui pourrait changer ta vie. N'hesite pas a ouvrir ton coeur et a saisir ces belles occasions. Tu es sur le point de vivre une periode pleine de succes et de bonheur, profite-en pleinement !",
        "En ce debut d'annee, les astres sont en faveur de votre reussite professionnelle. Vous aurez de nouvelles opportunites qui se presenteront a vous et vous saurez les saisir avec brio. Votre determination et votre creativite seront vos atouts pour atteindre vos objectifs. Cote coeur, de belles rencontres sont a prevoir. Vous pourriez tomber sous le charme d'une personne qui vous correspond parfaitement. Laissez-vous guider par vos emotions et profitez de ces moments magiques qui vous attendent. Prenez le temps de vous ouvrir aux autres, de partager et de vivre des experiences enrichissantes. Cette annee s'annonce pleine de surprises et de belles perspectives pour vous. Soyez confiant et laissez-vous porter par les energies positives qui vous entourent.",
        "Ton avenir s'annonce radieux, cher ami. Cote travail, les astres t'annoncent de belles opportunites professionnelles. Tu pourrais etre amene a prendre des responsabilites qui te meneront vers une reussite eclatante. Ta determination et ton serieux seront tes meilleurs allies pour atteindre tes objectifs. Dans ta vie amoureuse, de belles rencontres sont a prevoir dans les prochains mois. Tu pourrais faire la rencontre d'une personne speciale qui saura te combler de bonheur. Ouvre ton coeur et laisse-toi surprendre par les surprises que te reserve l'univers. Profite de ces moments pour t'epanouir et vivre pleinement tes emotions. Les astres sont de ton cote, a toi de saisir les opportunites qui s'offrent a toi.",
        "Cette semaine, les astres seront particulierement favorables pour votre travail. Vous pourrez enfin concretiser vos projets et voir vos efforts recompenses. Votre determination et votre perseverance seront vos meilleurs allies pour atteindre vos objectifs. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Que vous soyez en couple ou celibataire, l'amour sera au rendez-vous et vous pourriez bien etre surpris par une personne qui saura vous combler. Laissez-vous guider par vos emotions et laissez l'amour entrer dans votre vie sans retenue. Profitez de cette periode pour vous ouvrir a de nouvelles possibilites et laissez-vous surprendre par ce que l'avenir vous reserve.",
        "Les astres t'offrent de belles perspectives pour les jours a venir ! Cote travail, ta determination et ton professionnalisme seront recompenses. Tu pourrais etre amene(e) a relever de nouveaux defis, qui te permettront de mettre en avant tes talents. En amour, de belles rencontres sont a prevoir dans un futur proche. Laisse-toi porter par le destin et ouvre ton coeur a de nouvelles possibilites. Tu pourrais bien tomber sur une personne qui saura te faire vibrer et t'apporter du bonheur. N'hesite pas a sortir de ta zone de confort et a suivre ton instinct, les astres sont de ton cote !",
        "Dans les prochains jours, vous serez sous les influences astrales les plus favorables. Au travail, vous serez rempli d'energie et d'ambition, pret a relever tous les defis. Votre travail acharne sera recompense par une reussite eclatante et de nouvelles opportunites s'ouvriront a vous. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Que vous soyez en couple ou celibataire, l'amour sera au rendez-vous et vous fera vibrer de bonheur. Profitez de ces moments magiques et laissez-vous guider par les emotions. Cette periode sera egalement propice a la consolidation de vos relations amoureuses existantes. Vous serez en parfaite harmonie avec votre partenaire et rien ne pourra venir perturber votre bonheur.",
        "Tu traverses une periode de grands changements dans ta vie professionnelle. Les obstacles se dissipent et tu te sens plus confiant et motive que jamais. Tu vas bientot faire de belles rencontres qui t'apporteront de nouvelles opportunites et alliances fructueuses. Cote coeur, les astres te reservent de belles surprises. Tu pourrais faire la rencontre d'une personne speciale qui saura te comprendre et t'apporter un soutien precieux dans les moments difficiles. Profite de cette periode pour te laisser guider par ton coeur et ouvrir ton esprit a de nouvelles possibilites.",
        "Dans les prochains jours, votre vie professionnelle sera mise en avant. Vous serez reconnu pour vos competences et vos efforts, ce qui vous permettra de progresser rapidement. De nouvelles opportunites se presenteront a vous, n'hesitez pas a les saisir pour evoluer dans votre carriere. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Vous serez charme par une personne qui partagera vos valeurs et vos passions. Laissez-vous porter par vos sentiments et vivez pleinement cette nouvelle relation. Votre vie amoureuse sera remplie de bonheur et de complicite. Profitez de ces moments privilegies pour construire des projets a deux.",
        "Cette semaine, les astres te reservent de belles surprises. Cote travail, tu vas enfin recolter les fruits de tes efforts et etre reconnu a ta juste valeur. Une promotion ou une opportunite professionnelle excitante pourrait se presenter a toi. N'hesite pas a saisir ces chances et a croire en toi. Au niveau sentimental, de belles rencontres pourraient se profiler a l'horizon. Sois ouvert et laisse-toi surprendre par ces nouvelles personnes qui pourraient changer ta vie. Laisse-toi guider par ton coeur et tu seras comble(e) de bonheur.",
        "Cet horoscope annonce une periode favorable pour ta carriere, avec des opportunites d'evolution et de reussite a saisir. Tu auras l'energie et la determination pour atteindre tes objectifs professionnels et te demarquer de tes collegues. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Que tu sois celibataire ou en couple, tu seras entoure d'amour et de passion. Prends le temps de te laisser surprendre par ces nouvelles personnes qui pourraient bien changer ta vie. Profite de cette periode pour t'ouvrir a de nouvelles experiences et a de nouvelles emotions.",
        "Dans les prochains jours, les astres te reservent de belles opportunites sur le plan professionnel. Tu sauras faire preuve de creativite et de determination pour mener a bien tes projets. De nouvelles rencontres pourraient egalement se presenter sur ton chemin, aussi bien dans ta vie amoureuse que dans ton cercle social. Laisse-toi guider par ton intuition et ouvre-toi aux belles surprises qui t'attendent. Le ciel est clement, alors profite de cette periode pour avancer sereinement vers tes objectifs.",
        "Dans les semaines a venir, vous serez guide par une energie positive qui vous conduira vers de belles opportunites professionnelles. Vous gagnerez en confiance et en determination, ce qui vous permettra de realiser vos projets les plus ambitieux. Sur le plan sentimental, des rencontres inattendues pourraient bien bouleverser votre vie amoureuse. Restez ouvert et pret a saisir ces belles occasions qui s'offriront a vous. Laissez-vous porter par vos emotions et suivez votre coeur. Ces nouvelles relations pourraient bien etre les plus enrichissantes et les plus passionnantes de votre vie.",
        "Dans les prochains jours, votre carriere sera mise en avant et vous obtiendrez enfin la reconnaissance que vous meritez. Votre travail acharne et votre determination seront recompenses, alors n'ayez pas peur de relever de nouveaux defis. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Que ce soit en amour ou en amitie, de nouvelles personnes entreront dans votre vie et vous apporteront de la joie et du bonheur. Laissez-vous surprendre par ces rencontres qui pourraient bien changer votre vie. Profitez de ces moments pour vous ouvrir aux autres et decouvrir de nouvelles perspectives.",
        "Cette semaine, les astres te reservent de belles surprises tant sur le plan professionnel que sentimental. Au travail, tu seras inspire et motive, ce qui te permettra de realiser de grandes choses et de briller aupres de tes collegues et superieurs. Tu pourrais meme recevoir une proposition interessante pour evoluer dans ta carriere. Cote coeur, de nouvelles rencontres se profilent a l'horizon. Laisse-toi porter par les opportunites et tu pourrais bien tomber sur la personne qui fera battre ton coeur. Sois ouvert(e) et laisse la magie operer. Cette semaine s'annonce riche en emotions et en belles surprises, profite-en pleinement !",
        "Dans les jours a venir, les astres seront en faveur de votre carriere. Votre determination et votre perseverance seront recompensees, vous permettant de gravir les echelons et d'atteindre de nouveaux sommets professionnels. Vous serez egalement entoure d'une energie positive au travail, ce qui vous aidera a accomplir vos taches avec brio. Cote coeur, des rencontres prometteuses se profilent a l'horizon. Que vous soyez celibataire ou en couple, l'amour sera au rendez-vous. De belles opportunites de rencontrer de nouvelles personnes s'offriront a vous et pourraient bien bouleverser votre vie amoureuse. Soyez ouvert d'esprit et laissez la magie de l'amour operer. Des moments de bonheur et de complicite vous attendent.",
        "Cette semaine, les astres te reservent de belles opportunites dans le domaine professionnel. Tu pourrais recevoir une offre allechante ou etre reconnu pour tes talents et tes competences. Reste ouvert d'esprit et saisis les occasions qui se presentent a toi. Cote coeur, de nouvelles rencontres pourraient t'apporter de belles surprises. Tu pourrais faire la rencontre d'une personne qui te correspond parfaitement et avec qui tu partageras de bons moments. N'hesite pas a prendre des risques et laisse-toi guider par ton coeur. L'amour est au rendez-vous pour toi !",
        "Pour cette semaine, les astres sont alignes pour vous offrir de belles opportunites tant sur le plan professionnel que sentimental. Au travail, votre energie et votre determination seront recompensees par une promotion ou une augmentation. Vous pourrez egalement faire preuve de creativite et d'innovation pour mener a bien vos projets. Cote coeur, de nouvelles rencontres pourraient bouleverser votre vie amoureuse. Soyez ouvert(e) et laissez-vous seduire par ces belles surprises qui s'annoncent. Laissez votre coeur guider vos pas et vous pourriez vivre des moments inoubliables avec une personne speciale. Prenez le temps de cultiver ces nouvelles relations, elles pourraient vous apporter beaucoup de bonheur dans un futur proche.",
        "Ton avenir s'annonce radieux, cher ami ! Cote travail, tu vas faire des etincelles. Les opportunites ne manqueront pas et tu sauras les saisir avec brio. Ton talent et ta determination seront enfin reconnus a leur juste valeur. Mais ce n'est pas tout, car cote coeur, de belles rencontres t'attendent. Tu seras surpris par la complicite et l'harmonie qui s'installeront avec une personne speciale. Laisse-toi guider par tes emotions et tu verras que le bonheur est a portee de main. Profite de ces moments magiques et laisse ton coeur s'ouvrir a de nouvelles perspectives.",
        "Pour cette semaine a venir, les astres te reservent de belles opportunites tant sur le plan professionnel que sentimental. Au travail, tu auras l'occasion de briller et de te faire remarquer pour tes competences et tes idees novatrices. Tu pourrais meme recevoir une offre interessante de la part d'un employeur ou d'un partenaire. Cote coeur, de belles rencontres sont prevues pour toi dans un futur proche. Que ce soit lors d'une sortie entre amis ou d'une activite que tu aimes, tu pourrais croiser la route d'une personne qui fera battre ton coeur. Sois ouvert(e) et laisse-toi surprendre par cette belle rencontre qui pourrait changer ta vie.",
        "Dans les jours a venir, les astres te promettent de belles opportunites professionnelles. Tu vas enfin pouvoir mettre en avant tes competences et etre reconnu a ta juste valeur. N'hesite pas a prendre des risques et a sortir de ta zone de confort, cela te menera vers de nouveaux succes. Du cote du coeur, de belles rencontres sont prevues pour toi. Que ce soit dans ton cercle d'amis ou dans un contexte plus romantique, de nouvelles personnes vont entrer dans ta vie et t'apporter beaucoup de bonheur. Ouvre ton coeur et laisse-toi surprendre par ces belles rencontres a venir.",
        "Dans les prochains jours, les astres te reservent bien des surprises ! Cote travail, tu vas enfin recolter les fruits de tes efforts et etre reconnu a ta juste valeur. Une promotion ou une opportunite inattendue pourrait meme se presenter a toi. Dans le domaine du coeur, de belles rencontres sont prevues. Tu pourrais croiser la route d'une personne speciale qui te fera vibrer. Laisse-toi guider par tes emotions et profite de ces moments magiques qui s'annoncent. Le destin te reserve de belles surprises, sois pret a les accueillir avec enthousiasme !",
        "Cette semaine, les planetes te reservent de belles opportunites dans le domaine professionnel. Tu pourrais recevoir une proposition interessante ou etre reconnu pour ton travail acharne. Ne laisse pas passer ces occasions, car elles pourraient t'ouvrir de nouvelles portes vers la reussite. Cote coeur, de belles rencontres pourraient se presenter a toi dans un futur proche. Garde l'esprit ouvert et laisse-toi surprendre par ces nouvelles personnes qui pourraient apporter de la joie et de l'amour dans ta vie. N'aie pas peur de prendre des risques et de te laisser guider par ton coeur. Cette semaine s'annonce pleine de belles surprises et de succes dans tous les domaines de ta vie.",
        " Cet ete, les astres te reservent de belles surprises ! Cote travail, tu seras plein d'energie et d'ambition, pret a relever tous les defis. Ta determination et ton professionnalisme seront remarques, te permettant d'atteindre de nouveaux sommets. Une promotion ou une opportunite de carriere pourrait meme se presenter a toi. Mais n'oublie pas de prendre du temps pour toi et de te reposer, pour eviter le surmenage. En amour, les planetes s'alignent pour te faire vivre de merveilleuses rencontres. Que tu sois en couple ou celibataire, prepare-toi a vivre des moments intenses et passionnes. Tu pourrais meme faire la rencontre de quelqu'un de special qui te fera perdre la tete. Laisse-toi guider par ton coeur et profite de l'instant.",
        "Cher ami, les astres ont decide de te gater cette semaine ! Cote travail, tu vas enfin recolter les fruits de tes efforts. Ton travail acharne et ta determination seront reconnus et te permettront d'obtenir une promotion ou une augmentation bien meritee. Tu vas egalement faire de belles rencontres professionnelles qui pourront t'ouvrir de nouvelles opportunites. Dans ton coeur, les planetes t'annoncent de belles surprises. Si tu es celibataire, une rencontre inattendue pourrait bien bouleverser ta vie. Si tu es en couple, l'amour sera au rendez-vous avec des moments de complicite et de partage. Profite de cette periode favorable pour faire de nouvelles rencontres et t'ouvrir a de nouvelles experiences.",
        "Dans les prochains jours, votre vie professionnelle sera en pleine effervescence. Les astres vous encouragent a saisir les opportunites qui se presentent a vous et a ne pas avoir peur de prendre des risques. Votre travail sera recompense et vous pourriez meme recevoir une promotion ou une augmentation. Du cote de votre coeur, de belles rencontres sont prevues dans un futur proche. Que ce soit en amitie ou en amour, de nouvelles personnes entreront dans votre vie et vous apporteront joie et bonheur. N'hesitez pas a vous ouvrir aux autres et a laisser parler votre coeur. Une relation passionnante pourrait bien voir le jour.",
        "Dans les prochains jours, vous allez faire face a de nouvelles opportunites professionnelles. Votre determination et votre perseverance seront vos meilleurs allies pour atteindre vos objectifs. N'hesitez pas a sortir de votre zone de confort et a saisir les defis qui se presentent a vous. Cela pourrait vous mener vers une promotion ou une belle reconnaissance de votre travail. Du cote de votre coeur, de belles rencontres sont a prevoir dans un futur proche. Que vous soyez celibataire ou en couple, l'amour sera au rendez-vous. Soyez ouvert(e) aux nouvelles personnes et laissez-vous surprendre par les surprises que la vie vous reserve. Une connexion profonde et sincere pourrait se creer, apportant de la joie et de la stabilite a votre vie amoureuse. Profitez de ces moments magiques et laissez-vous guider par la musique.",
        "Cette semaine sera placee sous le signe de la reussite et de la chance dans le domaine professionnel. Vous serez motive et determine a atteindre vos objectifs, et votre travail acharne sera enfin recompense. De belles opportunites se presenteront a vous, n'hesitez pas a les saisir. Cote coeur, de belles rencontres sont prevues dans un futur proche. Que vous soyez en couple ou celibataire, l'amour sera au rendez-vous et vous ferez de magnifiques decouvertes. N'ayez pas peur de vous ouvrir aux autres, de nouvelles personnes pourraient changer votre vie. Profitez de cette periode pour cultiver de belles relations et partager de merveilleux moments.",
        "Dans les semaines a venir, les astres te reservent de belles surprises sur le plan professionnel. Tu pourrais etre amene(e) a faire une rencontre inattendue qui pourrait t'ouvrir de nouvelles portes et te permettre d'avancer dans ta carriere. Cette rencontre pourrait egalement te permettre de developper de nouvelles competences et de te depasser. Du cote de ton coeur, les astres annoncent egalement de belles rencontres. Tu pourrais croiser le chemin d'une personne qui te fera vibrer et avec qui tu partageras de beaux moments. Laisse-toi porter par le destin et ouvre-toi a de nouvelles possibilites.",
        "Dans les prochains jours, les astres te reservent de belles surprises dans ta vie professionnelle. Tu vas enfin recevoir la reconnaissance que tu merites et tes efforts seront recompenses. Tu auras egalement l'opportunite de te depasser et de montrer tes talents caches. Cote coeur, de belles rencontres sont a prevoir. Que tu sois celibataire ou en couple, une personne speciale va entrer dans ta vie et te faire vibrer. Laisse-toi guider par ton intuition et profite de ces moments magiques qui s'annoncent.",
        "Horoscope du jour : Aujourd'hui, les astres sont alignes pour vous offrir de belles opportunites sur le plan professionnel. Grace a votre determination et votre perseverance, vous pourriez obtenir une promotion ou une augmentation salariale tant meritee. Restez concentre et n'hesitez pas a faire valoir vos competences. Cote coeur, de belles rencontres pourraient se profiler dans un futur proche. Que vous soyez en couple ou celibataire, l'amour sera au rendez-vous. Laissez-vous porter par les emotions et ouvrez votre coeur a de nouvelles possibilites. Les astres vous encouragent a prendre des risques et a suivre votre intuition pour trouver le bonheur.",
        "Les astres sont alignes en votre faveur en ce moment. Cote travail, vous allez enfin recolter les fruits de vos efforts. Votre sens de l'organisation et votre perseverance seront reconnus et vous pourriez meme etre promu ou augmente. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Laissez-vous surprendre et osez prendre des risques, vous pourriez trouver l'amour la ou vous ne l'attendiez pas. Cette nouvelle relation sera empreinte de complicite et de passion. Profitez de cette periode favorable pour avancer et atteindre vos objectifs tant professionnels que personnels.",
        "Dans les prochains jours, tu seras particulierement chanceux dans le domaine professionnel. Les planetes sont alignees en ta faveur et tu seras recompense pour tous tes efforts. Tu pourrais meme recevoir une promotion ou une opportunite professionnelle interessante. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Tu seras attire par une personne qui te complete parfaitement et qui te fera vivre des moments inoubliables. Laisse-toi guider par ton coeur et n'hesite pas a prendre des risques, car cela pourrait mener a une belle histoire d'amour.",
        "Cette semaine, les astres sont en harmonie avec vous et vous apportent une dose de chance et de positivite dans votre vie. Cote travail, vous serez particulierement inspire et creatif, ce qui vous permettra de relever de nouveaux defis et de reussir brillamment. Vous pourriez meme recevoir une offre de promotion ou de nouvelles opportunites professionnelles. Dans votre vie amoureuse, de belles rencontres sont a prevoir dans un futur proche. Que vous soyez celibataire ou en couple, de merveilleux moments vous attendent avec la possibilite de trouver un amour sincere et durable. Ouvrez votre coeur et laissez-vous surprendre par les belles surprises que la vie vous reserve.",
        "Cette semaine, les astres te reservent de belles surprises, cher ami ! Du cote du travail, tu vas enfin recolter les fruits de tes efforts. Tu seras reconnu pour ton professionnalisme et tes competences, ce qui pourrait t'ouvrir de nouvelles opportunites. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Laisse-toi porter par le destin et tu pourrais bien trouver l'amour. Garde confiance en toi et en tes emotions, tout semble etre en place pour t'offrir une periode de bonheur et de reussite.",
        "Tu vas vivre une periode de grands changements dans ta vie professionnelle. Des opportunites excitantes vont se presenter a toi et tu sauras les saisir avec brio. Ta creativite et ton ambition seront tes meilleurs allies pour atteindre tes objectifs. Cote coeur, des rencontres inattendues vont te reserver de belles surprises. Tu vas croiser le chemin de personnes interessantes et passionnantes qui pourraient bien changer ta vie. N'hesite pas a ouvrir ton coeur et a te laisser surprendre par ces nouvelles rencontres qui pourraient bien etre les plus importantes de ta vie.",
        "Cette semaine, votre travail sera mis en avant et vous serez reconnu pour vos competences. Votre motivation et votre determination vous permettront de reussir dans tous vos projets. Les opportunites ne manqueront pas et vous serez en mesure de les saisir avec brio. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Que vous soyez celibataire ou en couple, l'amour sera au rendez-vous et vous apportera une nouvelle dose de bonheur. Soyez ouvert et laissez-vous surprendre par ces nouvelles personnes qui entreront dans votre vie.",
        "Cette semaine, les astres te reservent de belles surprises ! Dans le domaine professionnel, tu vas enfin recolter les fruits de tes efforts. Ton travail acharne sera reconnu et tu pourrais meme recevoir une promotion ou une opportunite interessante. Cote coeur, il y aura du mouvement ! Tu pourrais rencontrer une personne speciale qui fera battre ton coeur plus fort. Laisse-toi guider par tes emotions et profite de ces belles rencontres qui s'annoncent dans un futur proche.",
        "Cette semaine, les astres te reservent de belles opportunites tant sur le plan professionnel que sentimental. Au travail, tu seras tres creatif et tes idees seront appreciees par tes collegues et ton superieur. Tu pourrais meme etre choisi pour mener un projet important. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Que ce soit lors d'une soiree entre amis ou au detour d'une rue, tu pourrais croiser la route d'une personne speciale qui fera battre ton coeur. N'hesite pas a saisir ces occasions et a prendre des risques, car cela pourrait mener a une belle histoire d'amour.",
        "Les astres sont en harmonie pour toi cette semaine, cher ami. Dans le domaine professionnel, tu vas enfin recolter les fruits de tes efforts. Une promotion ou une opportunite de carriere excitante se profile a l'horizon. Tu te sentiras fier de toi et tu auras une grande confiance en tes competences. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Tu pourrais bien tomber sous le charme d'une personne qui te correspond parfaitement. Laisse-toi guider par tes emotions et laisse la magie operer. Profite de cette periode faste pour t'ouvrir aux autres et explorer de nouvelles relations. Les etoiles sont de ton cote, a toi de saisir les opportunites qui se presentent a toi.",
        "Cette semaine, les astres sont alignes pour toi ! Au travail, tu feras preuve d'une grande determination et tes efforts seront recompenses. Tu seras reconnu pour tes competences et de nouvelles opportunites s'offriront a toi. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Laisse-toi porter par tes emotions et n'hesite pas a prendre des risques, l'amour est a portee de main. Profite de cette periode pour t'ouvrir a de nouvelles personnes et vivre des moments inoubliables. Les planetes te reservent de belles surprises, sois pret a les accueillir avec le sourire !",
        "Aujourd'hui, les astres te sourient et t'offrent une journee remplie de belles opportunites. Cote travail, tu auras une energie debordante et une motivation sans faille pour atteindre tes objectifs. Tes efforts seront recompenses et tu pourrais meme recevoir une promotion ou une offre d'emploi interessante. Dans le domaine du coeur, de nouvelles rencontres s'annoncent. Laisse-toi surprendre par ces nouvelles personnes qui pourraient bien changer ta vie. Ouvre ton coeur et laisse l'amour entrer, car de belles histoires pourraient commencer dans un futur proche.",
        "Les astres te reservent de belles surprises pour ce mois-ci ! Du cote du travail, tu vas enfin recolter les fruits de tes efforts et etre reconnu pour tes competences. Une promotion ou une opportunite professionnelle inattendue pourrait se presenter a toi. N'hesite pas a saisir toutes les occasions qui se presentent ! Cote coeur, une rencontre passionnante t'attend. Tu vas faire la connaissance d'une personne qui va te faire vibrer et avec qui tu partageras de beaux moments. Laisse-toi porter par cette nouvelle histoire, elle pourrait bien etre l'amour de ta vie. Ne ferme pas ton coeur et laisse-toi surprendre par cette belle rencontre !",
        "Aujourd'hui, les astres te sourient et te promettent de belles opportunites dans ton travail. Tu auras la chance de mettre en avant tes competences et d'etre reconnu a ta juste valeur. Une promotion ou une augmentation de salaire pourrait meme etre envisageable. Cote coeur, de nouvelles rencontres pourraient bien bouleverser ta vie. Sois ouvert et pret a saisir ces belles opportunites qui s'offrent a toi. L'amour sera au rendez-vous et tu pourrais bien rencontrer une personne qui va te faire vibrer. Laisse-toi guider par tes emotions et profite de ces moments magiques.",
        "Dans les prochains jours, vous serez porte(e) par une energie positive dans votre vie professionnelle. Les astres vous offrent de belles opportunites de reussite et de reconnaissance. Avec votre determination et votre perseverance, vous pourrez atteindre vos objectifs et meme depasser vos attentes. Cependant, ne negligez pas votre vie amoureuse car de belles rencontres pourraient se presenter a vous. Soyez ouvert(e) a de nouveaux sentiments et laissez-vous surprendre par ce que le destin vous reserve. Laissez votre coeur guider vos pas et vous serez comble(e) dans toutes les spheres de votre vie.",
        "Dans les prochains jours, les astres te reservent de belles surprises, cher ami. Cote travail, une opportunite inattendue pourrait se presenter a toi. N'hesite pas a saisir cette chance et a mettre en avant tes talents, cela pourrait t'ouvrir de nouvelles portes dans ta carriere. Dans la sphere amoureuse, des rencontres prometteuses pourraient egalement se profiler a l'horizon. Que ce soit lors d'une soiree entre amis ou au detour d'une rue, l'amour pourrait frapper a ta porte. Ne ferme pas ton coeur et laisse-toi porter par ces belles rencontres qui pourraient bien changer ta vie.",
        "Cette semaine, les astres te reservent de belles surprises ! Dans le domaine du travail, tu vas enfin recolter les fruits de tous tes efforts. Ton travail acharne va etre recompense par une promotion ou une augmentation de salaire. Tu vas egalement faire de belles rencontres professionnelles qui pourront t'ouvrir de nouvelles portes. Cote coeur, les etoiles annoncent de belles rencontres dans un futur proche. Que tu sois celibataire ou en couple, tu seras charme(e) par la personne qui croisera ton chemin. Une relation passionnante et epanouissante pourrait bien se dessiner pour toi. Laisse-toi porter par le destin et n'hesite pas a prendre des risques pour vivre intensement ces moments magiques.",
        "Dans les prochains jours, les astres te reservent de belles surprises. Cote travail, tu seras recompense pour tes efforts et ton devouement. Une opportunite professionnelle interessante se presentera a toi, n'hesite pas a la saisir. Ta determination et ta perseverance seront tes atouts pour reussir. Dans ta vie amoureuse, de belles rencontres sont a prevoir. Laisse-toi guider par ton intuition et ouvre ton coeur, tu pourrais etre agreablement surpris. Profite de ces moments de bonheur qui s'annoncent, car ils te donneront l'energie necessaire pour atteindre tes objectifs. Reste confiant, les astres sont avec toi.",
        "Cette semaine, les astres se realignent pour vous apporter de bonnes nouvelles dans votre vie professionnelle. Vous allez enfin obtenir la reconnaissance que vous meritez et votre travail sera recompense. Ne relachez pas vos efforts, car cela vous ouvrira de nouvelles opportunites pour votre carriere. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Laissez-vous porter par la magie de l'amour et soyez ouvert(e) aux nouvelles experiences. Les astres vous reservent de belles surprises et vous pourriez bien rencontrer votre ame soeur. N'ayez pas peur de vous laisser aller et de suivre votre coeur, vous ne le regretterez pas.",
        "Cette semaine, les astres te reservent de belles opportunites dans le domaine professionnel. Grace a ton travail acharne et ta determination, tu pourrais etre remarque par tes superieurs et obtenir une promotion tant meritee. Ne laisse pas passer cette chance et montre de quoi tu es capable. Dans le domaine amoureux, de belles rencontres pourraient se profiler a l'horizon. Sois ouvert(e) aux nouvelles rencontres et laisse-toi surprendre par le destin. Qui sait, peut-etre trouveras-tu enfin la personne qui te correspond vraiment. Garde confiance en toi et en l'avenir, de belles surprises t'attendent.",
        "Cette semaine, les astres sont alignes pour toi ! Cote travail, tu pourrais etre confronte a des defis, mais grace a ta determination et a ton esprit d'equipe, tu reussiras a les surmonter avec brio. Une promotion ou une nouvelle opportunite pourrait meme se presenter a toi, alors reste ouvert aux possibilites ! Sur le plan amoureux, de belles rencontres pourraient se profiler a l'horizon. Laisse-toi guider par ton intuition et n'hesite pas a prendre des risques pour trouver l'amour. Qui sait, peut-etre tomberas-tu sous le charme d'une personne aussi passionnee que toi. Alors garde le sourire et laisse l'amour te surprendre !",
        "Dans les prochains mois, les astres te reservent de belles surprises dans ta vie professionnelle. Grace a ton devouement et ta perseverance, tu seras recompense par une promotion ou une opportunite d'evolution. Ne crains pas les defis, car ils te meneront vers de nouveaux horizons. Cote coeur, de belles rencontres sont a prevoir. Laisse-toi surprendre par l'amour qui arrivera dans ta vie et qui te fera vibrer comme jamais auparavant. Les astres te poussent a laisser tomber tes barrieres et a te laisser guider par tes emotions. Une belle histoire t'attend, ouvre ton coeur et profite de chaque instant.",
        "Cette semaine, les astres t'annoncent une periode propice pour ta vie professionnelle. Des opportunites de developpement se presentent a toi, a toi de saisir les bonnes occasions et de faire preuve de determination pour atteindre tes objectifs. Tu sauras faire preuve de creativite et de perseverance pour mener a bien tes projets. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Les planetes favorisent les echanges et les nouvelles rencontres qui pourraient bien bouleverser ta vie amoureuse. Ouvre ton coeur et laisse-toi surprendre par ces nouvelles personnes qui pourraient te faire vivre des moments intenses et passionnes. Garde l'esprit ouvert et laisse la magie de l'amour operer.",
        "Aujourd'hui, les astres te promettent une journee pleine de succes dans le domaine professionnel. Grace a ta determination et ton travail acharne, tu pourras atteindre tes objectifs et meme depasser tes attentes. Les opportunites seront nombreuses, n'hesite pas a saisir celles qui se presentent a toi. Cote coeur, les planetes t'annoncent de belles rencontres dans un futur proche. Que ce soit par hasard ou lors d'un evenement, tu pourrais croiser une personne qui bouleversera ta vie. Laisse-toi porter par tes emotions et ouvre-toi a de nouvelles possibilites. L'amour sera au rendez-vous et pourrait meme t'apporter de grandes surprises. Profite de cette journee pour semer les graines de l'amour et laisser eclore de belles histoires.",
        "Cette semaine, les astres te reservent de belles surprises cote travail. Tu seras motive(e) et plein(e) d'energie pour mener a bien tes projets. Tu verras les resultats de tes efforts et ta determination sera reconnue par tes superieurs. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Tu seras ouvert(e) aux nouvelles experiences et cela pourrait te mener vers une personne speciale. N'hesite pas a saisir les opportunites qui se presentent a toi, l'amour pourrait bien etre au rendez-vous.",
        "Dans les semaines a venir, vous serez porte(e) par une energie positive et dynamique dans votre vie professionnelle. Votre perseverance et votre creativite seront recompensees par de belles opportunites et des avancees significatives dans votre carriere. N'hesitez pas a prendre des risques et a sortir de votre zone de confort, cela vous menera vers de nouveaux succes. Cote coeur, de belles rencontres sont a prevoir dans un futur proche. Vous pourriez etre surpris(e) par une personne qui vous correspond parfaitement et qui vous apportera beaucoup de bonheur. Laissez-vous guider par vos emotions et soyez ouvert(e) aux nouvelles experiences. Cette relation pourrait bien evoluer vers une histoire d'amour sincere et passionnee. Profitez de ces moments intenses et laissez-vous apprecier ce qui vient.",
    ]


    signs = [
        (1,20,"Capricorne"),
        (2,18,"Verseau"),
        (3,20,"Poissons"),
        (4,20,"Belier"),
        (5,21,"Taureau"),
        (6,21,"Gemeaux"),
        (7,22,"Cancer"),
        (8,23,"Lion"),
        (9,23,"Vierge"),
        (10,23,"Balance"),
        (11,22,"Scorpion"),
        (12,22,"Sagittaire"),
        (12,31,"Capricorne"),
    ]
